class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """
        Sets a transaction in the transaction pool.
        :param transaction:
        :return:
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Finds a transaction generated by the address in the transaction pool.
        :param address:
        :return:
        """
        for transaction in self.transaction_map.values():
            if transaction.input[0]['address'] == address:
                return transaction
        return None

    def transaction_data(self):
        """
        Returns the transactions of the transaction pool represented in their
        JSON serialized form.
        """
        return list(map(
            lambda transaction: transaction.to_json(),
            self.transaction_map.values()
        ))

    def clear_blockchain_transactions(self, blockchain):
        """
        Delete blockchain recorded transactions from the transaction pool.
        """
        for block in blockchain.chain:
            for transaction in block.data:
                try:
                    del self.transaction_map[transaction['id']]
                except KeyError:
                    pass
